# Generated by Django 4.2.1 on 2023-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_post_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Ürün Görseli'),
        ),
    ]
