# Generated by Django 4.2.1 on 2023-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_alter_post_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oluşturma Zamanı'),
        ),
    ]
