# Generated by Django 4.2.1 on 2023-08-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0018_comment_profil_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profil',
        ),
    ]
